name       : yazi
version    : 25.5.31
release    : 1
source     :
  - https://github.com/sxyazi/yazi/archive/refs/tags/v25.5.31.tar.gz : 4d005e7c3f32b5574d51ab105597f3da3a4be2f7b5cd1bcb284143ad38253ed4
homepage   : https://yazi-rs.github.io
license    : MIT
component  : system.utils
summary    : Blazingly fast terminal file manager
description: |
  Yazi is a terminal file manager written in Rust with async I/O, rich preview,
  and extensibility through plugins and themes.
networking : true
builddeps  :
  - imagemagick
  - rust
rundeps    :
  - file
setup      : |
  %cargo_fetch

build: |
  YAZI_GEN_COMPLETIONS=true %cargo_build

install: |
  %cargo_install yazi ya
  install -Dm644 "assets/yazi.desktop" "$installdir/usr/share/applications/yazi.desktop"

  # Install icons
  for r in 16 24 32 48 64 128 256; do
    install -dm755 "$installdir/usr/share/icons/hicolor/${r}x${r}/apps"
    magick assets/logo.png -resize "${r}x${r}" "$installdir/usr/share/icons/hicolor/${r}x${r}/apps/yazi.png"
  done

  # Install shell completions
  cd yazi-boot/completions
  install -Dm644 "yazi.bash" "$installdir/usr/share/bash-completion/completions/yazi"
  install -Dm644 "yazi.fish" "$installdir/usr/share/fish/vendor_completions.d/yazi.fish"
  install -Dm644 "_yazi" "$installdir/usr/share/zsh/site-functions/_yazi"
